/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * seat.java
 *
 * Created on 18 Oct, 2011, 2:23:33 PM
 */
package javaapplication2;

/**
 *
 * @author Mahek Chheda
 */
import java.awt.Color;
import java.sql.*;
import javax.swing.JLayeredPane;
public class copyseat extends javax.swing.JFrame {

    /** Creates new form seat */
    Connection c;
    ResultSet rs;
    Statement s1;
    boolean flag[];
    static String usr,bal;
    public copyseat() {
         try {
             
              flag = new boolean[77];
              for(int i=0; i<77; i++) {
                  flag[i] = false;
              }
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver").newInstance();
            c = DriverManager.getConnection(
                          "jdbc:odbc:Driver={Microsoft Access Driver (*.mdb)};DBQ=f:/customer.mdb");
            s1 = c.createStatement();
            retreive.usr=usr;
            retreive.bal=bal;
      //  bal=si.getBalance();
        } catch (Exception e) {
            System.out.println("Y!!!!!!!");
        }
         
        initComponents();
        
          

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton2 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jButton20 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jButton76 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 600, 400));
        getContentPane().setLayout(null);

        jLabel1.setText("Screen No:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(767, 43, 62, 14);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 8));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(833, 36, 41, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SCREEN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(620, 506, 594, 26);

        jLabel3.setText("Current Balance:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 110, 170, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(390, 106, 102, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Category", "Silver", "Gold", "Platinum" }));

        for(int i=0; i<jLayeredPane2.getComponentCount(); i++) {
            jLayeredPane3.getComponent(i).setEnabled(false);
            jLayeredPane2.getComponent(i).setEnabled(false);
        }
        for(int i=0;i<jLayeredPane4.getComponentCount();i++){
            jLayeredPane4.getComponent(i).setEnabled(false);
        }
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(390, 210, 102, 20);

        jLabel4.setText("Category");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 210, 140, 30);

        jButton77.setText("Recharge");
        getContentPane().add(jButton77);
        jButton77.setBounds(10, 568, 356, 28);

        jButton78.setText("Book");
        jButton78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton78ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton78);
        jButton78.setBounds(390, 566, 320, 32);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1114, 0, 100, 100);

        jLayeredPane1.setEnabled(false);

        jButton2.setText("jButton2");
        setBackground(Color.red);
        jButton2.setBounds(0, 50, 73, 23);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton79.setText("jButton79");
        setBackground(Color.red);
        jButton79.setBounds(0, 0, 79, 23);
        jLayeredPane1.add(jButton79, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(390, 343, 134, 100);

        jLayeredPane2.setEnabled(false);

        jButton20.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton20.setText("2");
        buttonGroup1.add(jButton20);
        jButton20.setBounds(50, 50, 50, 30);
        jLayeredPane2.add(jButton20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton5.setText("6");
        buttonGroup1.add(jButton5);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(270, 10, 41, 30);
        jLayeredPane2.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton4.setText("4");
        buttonGroup1.add(jButton4);
        jButton4.setBounds(180, 10, 39, 30);
        jLayeredPane2.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton3.setText("3");
        buttonGroup1.add(jButton3);
        jButton3.setBounds(100, 10, 50, 30);
        jLayeredPane2.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        A2.setFont(new java.awt.Font("Tahoma", 0, 8));
        A2.setText("2");
        buttonGroup1.add(A2);
        A2.setBounds(48, 10, 50, 30);
        jLayeredPane2.add(A2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton7.setText("7");
        buttonGroup1.add(jButton7);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.setBounds(320, 10, 44, 30);
        jLayeredPane2.add(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton6.setText("5");
        buttonGroup1.add(jButton6);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(230, 10, 37, 30);
        jLayeredPane2.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton17.setText("7");
        buttonGroup1.add(jButton17);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jButton17.setBounds(320, 50, 44, 30);
        jLayeredPane2.add(jButton17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton15.setText("9");
        buttonGroup1.add(jButton15);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jButton15.setBounds(450, 50, 43, 30);
        jLayeredPane2.add(jButton15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton16.setText("5");
        buttonGroup1.add(jButton16);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jButton16.setBounds(220, 50, 39, 30);
        jLayeredPane2.add(jButton16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton13.setText("4");
        buttonGroup1.add(jButton13);
        jButton13.setBounds(180, 50, 39, 30);
        jLayeredPane2.add(jButton13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton14.setText("8");
        buttonGroup1.add(jButton14);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jButton14.setBounds(410, 50, 41, 30);
        jLayeredPane2.add(jButton14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton11.setText("3");
        buttonGroup1.add(jButton11);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jButton11.setBounds(99, 50, 50, 30);
        jLayeredPane2.add(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton12.setText("6");
        buttonGroup1.add(jButton12);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jButton12.setBounds(270, 50, 41, 30);
        jLayeredPane2.add(jButton12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton9.setText("9");
        buttonGroup1.add(jButton9);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jButton9.setBounds(450, 10, 43, 30);
        jLayeredPane2.add(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton10.setText("10");
        buttonGroup1.add(jButton10);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jButton10.setBounds(500, 10, 46, 30);
        jLayeredPane2.add(jButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton19.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton19.setText("1");
        buttonGroup1.add(jButton19);
        jButton19.setBounds(0, 50, 50, 30);
        jLayeredPane2.add(jButton19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton18.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton18.setText("10");
        buttonGroup1.add(jButton18);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jButton18.setBounds(500, 50, 46, 30);
        jLayeredPane2.add(jButton18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton1.setText("1");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.setBounds(0, 10, 48, 30);
        jLayeredPane2.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jButton1.getAccessibleContext().setAccessibleParent(jLayeredPane1);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton8.setText("8");
        buttonGroup1.add(jButton8);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.setBounds(410, 10, 41, 30);
        jLayeredPane2.add(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane2);
        jLayeredPane2.setBounds(650, 140, 568, 100);

        jLayeredPane3.setEnabled(false);
        jLayeredPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane3MouseClicked(evt);
            }
        });

        jButton33.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton33.setText("3");
        jButton33.setBounds(90, 50, 39, 30);
        jLayeredPane3.add(jButton33, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton34.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton34.setText("8");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jButton34.setBounds(420, 50, 43, 30);
        jLayeredPane3.add(jButton34, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton31.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton31.setText("6");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jButton31.setBounds(280, 50, 40, 30);
        jLayeredPane3.add(jButton31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton32.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton32.setText("9");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jButton32.setBounds(470, 50, 44, 30);
        jLayeredPane3.add(jButton32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton37.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton37.setText("2");
        jButton37.setBounds(50, 50, 37, 30);
        jLayeredPane3.add(jButton37, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton35.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton35.setText("7");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jButton35.setBounds(330, 50, 44, 30);
        jLayeredPane3.add(jButton35, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton36.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton36.setText("5");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jButton36.setBounds(230, 50, 37, 30);
        jLayeredPane3.add(jButton36, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton40.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton40.setText("4");
        jButton40.setBounds(190, 50, 37, 30);
        jLayeredPane3.add(jButton40, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton39.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton39.setText("10");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jButton39.setBounds(520, 50, 46, 30);
        jLayeredPane3.add(jButton39, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton38.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton38.setText("1");
        jButton38.setBounds(0, 50, 37, 30);
        jLayeredPane3.add(jButton38, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton21.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton21.setText("7");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jButton21.setBounds(330, 10, 44, 30);
        jLayeredPane3.add(jButton21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton22.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton22.setText("8");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jButton22.setBounds(420, 10, 43, 30);
        jLayeredPane3.add(jButton22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton23.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton23.setText("4");
        jButton23.setBounds(180, 10, 39, 30);
        jLayeredPane3.add(jButton23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton24.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton24.setText("5");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jButton24.setBounds(230, 10, 39, 30);
        jLayeredPane3.add(jButton24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton25.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton25.setText("2");
        jButton25.setBounds(50, 10, 40, 30);
        jLayeredPane3.add(jButton25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton26.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton26.setText("1");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jButton26.setBounds(0, 10, 41, 30);
        jLayeredPane3.add(jButton26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton27.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton27.setText("10");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jButton27.setBounds(520, 10, 46, 30);
        jLayeredPane3.add(jButton27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton28.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton28.setText("3");
        jButton28.setBounds(100, 10, 39, 30);
        jLayeredPane3.add(jButton28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton30.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton30.setText("6");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jButton30.setBounds(280, 10, 43, 30);
        jLayeredPane3.add(jButton30, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton29.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton29.setText("9");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jButton29.setBounds(470, 10, 44, 30);
        jLayeredPane3.add(jButton29, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane3);
        jLayeredPane3.setBounds(640, 230, 578, 100);

        jLayeredPane4.setEnabled(false);

        jButton76.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton76.setText("4");
        jButton76.setBounds(150, 90, 41, 30);
        jLayeredPane4.add(jButton76, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton75.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton75.setText("11");
        jButton75.setBounds(480, 90, 41, 30);
        jLayeredPane4.add(jButton75, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton74.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton74.setText("12");
        jButton74.setBounds(530, 90, 41, 30);
        jLayeredPane4.add(jButton74, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton64.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton64.setText("8");
        jButton64.setBounds(290, 50, 41, 30);
        jLayeredPane4.add(jButton64, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton63.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton63.setText("6");
        jButton63.setBounds(240, 50, 40, 30);
        jLayeredPane4.add(jButton63, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton66.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton66.setText("9");
        jButton66.setBounds(380, 90, 41, 30);
        jLayeredPane4.add(jButton66, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton65.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton65.setText("2");
        jButton65.setBounds(60, 90, 46, 30);
        jLayeredPane4.add(jButton65, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton67.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton67.setText("10");
        jButton67.setBounds(430, 90, 41, 30);
        jLayeredPane4.add(jButton67, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton68.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton68.setText("6");
        jButton68.setBounds(240, 90, 40, 30);
        jLayeredPane4.add(jButton68, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton69.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton69.setText("1");
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton69ActionPerformed(evt);
            }
        });
        jButton69.setBounds(10, 90, 46, 30);
        jLayeredPane4.add(jButton69, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton70.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton70.setText("5");
        jButton70.setBounds(200, 90, 41, 30);
        jLayeredPane4.add(jButton70, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton71.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton71.setText("8");
        jButton71.setBounds(340, 90, 41, 30);
        jLayeredPane4.add(jButton71, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton72.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton72.setText("7");
        jButton72.setBounds(290, 90, 41, 30);
        jLayeredPane4.add(jButton72, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton73.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton73.setText("3");
        jButton73.setBounds(110, 90, 40, 30);
        jLayeredPane4.add(jButton73, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton56.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton56.setText("12");
        jButton56.setBounds(480, 50, 41, 30);
        jLayeredPane4.add(jButton56, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton55.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton55.setText("9");
        jButton55.setBounds(340, 50, 41, 30);
        jLayeredPane4.add(jButton55, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton54.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton54.setText("10");
        jButton54.setBounds(380, 50, 41, 30);
        jLayeredPane4.add(jButton54, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton53.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton53.setText("11");
        jButton53.setBounds(430, 50, 41, 30);
        jLayeredPane4.add(jButton53, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton52.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton52.setText("12");
        jButton52.setBounds(530, 20, 41, 30);
        jLayeredPane4.add(jButton52, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton61.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton61.setText("4");
        jButton61.setBounds(150, 50, 41, 30);
        jLayeredPane4.add(jButton61, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton62.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton62.setText("5");
        jButton62.setBounds(200, 50, 41, 30);
        jLayeredPane4.add(jButton62, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton59.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton59.setText("2");
        jButton59.setBounds(60, 50, 46, 30);
        jLayeredPane4.add(jButton59, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton60.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton60.setText("3");
        jButton60.setBounds(110, 50, 40, 30);
        jLayeredPane4.add(jButton60, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton57.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton57.setText("13");
        jButton57.setBounds(530, 50, 41, 30);
        jLayeredPane4.add(jButton57, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton58.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton58.setText("1");
        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });
        jButton58.setBounds(10, 50, 46, 30);
        jLayeredPane4.add(jButton58, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton46.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton46.setText("6");
        jButton46.setBounds(240, 20, 40, 30);
        jLayeredPane4.add(jButton46, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton45.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton45.setText("5");
        jButton45.setBounds(200, 20, 41, 30);
        jLayeredPane4.add(jButton45, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton42.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton42.setText("2");
        jButton42.setBounds(60, 20, 46, 30);
        jLayeredPane4.add(jButton42, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton41.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton41.setText("1");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jButton41.setBounds(10, 20, 46, 30);
        jLayeredPane4.add(jButton41, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton44.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton44.setText("4");
        jButton44.setBounds(150, 20, 41, 30);
        jLayeredPane4.add(jButton44, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton43.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton43.setText("3");
        jButton43.setBounds(110, 20, 40, 30);
        jLayeredPane4.add(jButton43, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton48.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton48.setText("8");
        jButton48.setBounds(340, 20, 41, 30);
        jLayeredPane4.add(jButton48, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton49.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton49.setText("9");
        jButton49.setBounds(380, 20, 41, 30);
        jLayeredPane4.add(jButton49, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton50.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton50.setText("10");
        jButton50.setBounds(430, 20, 41, 30);
        jLayeredPane4.add(jButton50, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton51.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton51.setText("11");
        jButton51.setBounds(480, 20, 41, 30);
        jLayeredPane4.add(jButton51, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton47.setFont(new java.awt.Font("Tahoma", 0, 8));
        jButton47.setText("7");
        jButton47.setBounds(290, 20, 41, 30);
        jLayeredPane4.add(jButton47, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane4);
        jLayeredPane4.setBounds(635, 318, 579, 140);

        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(90, 160, 59, 20);

        pack();
    }// </editor-fold>

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
// TODO add your handling code here:
}                                           

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
// TODO add your handling code here:
    if (flag[7])
{
    jButton7.setBackground(new Color(240, 240, 240));
    flag[7] = false;
}else {
    jButton7.setBackground(new Color(255, 0, 0));
    flag[7] = true;
}
}                                        

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
// TODO add your handling code here:
    if (flag[5])
{
    jButton5.setBackground(new Color(240, 240, 240));
    flag[5] = false;
}else {
    jButton5.setBackground(new Color(255, 0, 0));
    flag[5] = true;
}
}                                        

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
// TODO add your handling code here:
    if (flag[6])
{
    jButton6.setBackground(new Color(240, 240, 240));
    flag[6] = false;
}else {
    jButton6.setBackground(new Color(255, 0, 0));
    flag[6] = true;
}
}                                        

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
// TODO add your handling code here:
    if (flag[8])
{
    jButton8.setBackground(new Color(240, 240, 240));
    flag[8] = false;
}else {
    jButton8.setBackground(new Color(255, 0, 0));
    flag[8] = true;
}
}                                        

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
// TODO add your handling code here:
    if (flag[9])
{
    jButton9.setBackground(new Color(240, 240, 240));
    flag[9] = false;
}else {
    jButton9.setBackground(new Color(255, 0, 0));
    flag[9] = true;
}
}                                        

private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
    if (flag[10])
{
    jButton10.setBackground(new Color(240, 240, 240));
    flag[10] = false;
}else {
    jButton10.setBackground(new Color(255, 0, 0));
    flag[10] = true;
}
}                                         

private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
    if (flag[12])
{
    jButton12.setBackground(new Color(240, 240, 240));
    flag[12] = false;
}else {
    jButton12.setBackground(new Color(255, 0, 0));
    flag[12] = true;
}
}                                         

private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO addif (flag[26])
if(flag[14])
{
    jButton14.setBackground(new Color(240, 240, 240));
    flag[14] = false;
}else {
    jButton14.setBackground(new Color(255, 0, 0));
    flag[14] = true;
}
}                                         

private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO addif (flag[26])
    if(flag[15])
{
    jButton15.setBackground(new Color(240, 240, 240));
    flag[15] = false;
}else {
    jButton15.setBackground(new Color(255, 0, 0));
    flag[15] = true;
} 
}                                         

private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO addif (flag[26])
    if(flag[16])
{
    jButton16.setBackground(new Color(240, 240, 240));
    flag[16] = false;
}else {
    jButton16.setBackground(new Color(255, 0, 0));
    flag[16] = true;
} 
}                                         

private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO adif (flag[26])
    if(flag[17])
{
    jButton17.setBackground(new Color(240, 240, 240));
    flag[17] = false;
}else {
    jButton17.setBackground(new Color(255, 0, 0));
    flag[17] = true;
}
}                                         

private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO addif (flag[26])
    if(flag[18])
{
    jButton18.setBackground(new Color(240, 240, 240));
    flag[18] = false;
}else {
    jButton18.setBackground(new Color(255, 0, 0));
    flag[18] = true;
} 
}                                         

private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
     if(flag[21])
{
    jButton21.setBackground(new Color(240, 240, 240));
    flag[21] = false;
}else {
    jButton21.setBackground(new Color(255, 0, 0));
    flag[21] = true;
} 
}                                         

private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
     if(flag[21])
{
    jButton21.setBackground(new Color(240, 240, 240));
    flag[21] = false;
}else {
    jButton21.setBackground(new Color(255, 0, 0));
    flag[21] = true;
} 
}                                         

private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
       if(flag[24])
{
    jButton24.setBackground(new Color(240, 240, 240));
    flag[24] = false;
}else {
    jButton24.setBackground(new Color(255, 0, 0));
    flag[24] = true;
} 
}                                         

private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
       if(flag[27])
{
    jButton27.setBackground(new Color(240, 240, 240));
    flag[27] = false;
}else {
    jButton27.setBackground(new Color(255, 0, 0));
    flag[27] = true;
} 
}                                         

private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
       if(flag[29])
{
    jButton29.setBackground(new Color(240, 240, 240));
    flag[29] = false;
}else {
    jButton29.setBackground(new Color(255, 0, 0));
    flag[29] = true;
} 
}                                         

private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
       if(flag[30])
{
    jButton30.setBackground(new Color(240, 240, 240));
    flag[30] = false;
}else {
    jButton30.setBackground(new Color(255, 0, 0));
    flag[30] = true;
} 
}                                         

private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
       if(flag[31])
{
    jButton31.setBackground(new Color(240, 240, 240));
    flag[31] = false;
}else {
    jButton31.setBackground(new Color(255, 0, 0));
    flag[31] = true;
} 
}                                         

private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
       if(flag[32])
{
    jButton32.setBackground(new Color(240, 240, 240));
    flag[32] = false;
}else {
    jButton32.setBackground(new Color(255, 0, 0));
    flag[32] = true;
} 
}                                         

private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
       if(flag[34])
{
    jButton34.setBackground(new Color(240, 240, 240));
    flag[34] = false;
}else {
    jButton34.setBackground(new Color(255, 0, 0));
    flag[34] = true;
} 
}                                         

private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
       if(flag[35])
{
    jButton35.setBackground(new Color(240, 240, 240));
    flag[35] = false;
}else {
    jButton35.setBackground(new Color(255, 0, 0));
    flag[35] = true;
} 
}                                         

private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
       if(flag[36])
{
    jButton36.setBackground(new Color(240, 240, 240));
    flag[36] = false;
}else {
    jButton36.setBackground(new Color(255, 0, 0));
    flag[36] = true;
} 
}                                         

private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
       if(flag[39])
{
    jButton39.setBackground(new Color(240, 240, 240));
    flag[39] = false;
}else {
    jButton39.setBackground(new Color(255, 0, 0));
    flag[39] = true;
} 
}                                         

private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
       if(flag[41])
{
    jButton41.setBackground(new Color(240, 240, 240));
    flag[41] = false;
}else {
    jButton41.setBackground(new Color(255, 0, 0));
    flag[41] = true;
} 
}                                         

private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
       if(flag[58])
{
    jButton58.setBackground(new Color(240, 240, 240));
    flag[58] = false;
}else {
    jButton58.setBackground(new Color(255, 0, 0));
    flag[58] = true;
} 
}                                         

private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
       if(flag[69])
{
    jButton69.setBackground(new Color(240, 240, 240));
    flag[69] = false;
}else {
    jButton21.setBackground(new Color(255, 0, 0));
    flag[69] = true;
} 
}                                         

private void jButton78ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
    int d=0;
   jTextField2.setText(retreive.bal);
    //int bal2=Integer.parseInt(retreive.bal);
    int bal2=1000;
    for(int i=0;i<jLayeredPane2.getComponentCount();i++)
    {
        if(jLayeredPane2.getComponent(i).getBackground().equals(Color.red))
                {
                    d++;
                    bal2-=100;
                    jLayeredPane2.getComponent(i).setVisible(false);
                }
    }
    for(int i=0;i<jLayeredPane3.getComponentCount();i++)
    {
        if(jLayeredPane3.getComponent(i).getBackground().equals(Color.red))
                {
                    d++;
                    bal2-=150;
                    System.out.println("CHIT");
                         
                }
    }
    for(int i=0;i<jLayeredPane4.getComponentCount();i++)
    {
        if(jLayeredPane4.getComponent(i).getBackground().equals(Color.red))
                {
                    d++;
                    bal2-=200;
                }
    }
    try
    {
        String r=""+bal2;
        jTextField1.setText(r);
         // s1.execute("update customer set Balance='"+r+"' where Username='"+usr+"';");
    }
    catch(Exception e)
    {
        
        System.out.println(e);
    }
}                                         

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
// TODO add your handling code here:
    //System.out.println("done");
    String cat=""+jComboBox1.getSelectedItem();
    System.out.println(cat);
    if(cat.equalsIgnoreCase("platinum"))
    {
     for(int i=0; i<jLayeredPane2.getComponentCount(); i++) {
        jLayeredPane3.getComponent(i).setEnabled(false);
        jLayeredPane2.getComponent(i).setEnabled(true);
        }
        for(int i=0;i<jLayeredPane4.getComponentCount();i++){
        jLayeredPane4.getComponent(i).setEnabled(false);
        }
    }
    else if(cat.equalsIgnoreCase("gold"))
    {
        for(int i=0; i<jLayeredPane2.getComponentCount(); i++) {
        jLayeredPane3.getComponent(i).setEnabled(true);
        jLayeredPane2.getComponent(i).setEnabled(false);
        }
        for(int i=0;i<jLayeredPane4.getComponentCount();i++){
        jLayeredPane4.getComponent(i).setEnabled(false);
        }
    }
    else if(cat.equalsIgnoreCase("silver"))
    {for(int i=0; i<jLayeredPane2.getComponentCount(); i++) {
        jLayeredPane3.getComponent(i).setEnabled(false);
        jLayeredPane2.getComponent(i).setEnabled(false);
        }
        for(int i=0;i<jLayeredPane4.getComponentCount();i++){
        jLayeredPane4.getComponent(i).setEnabled(true);
        }
    }
    else
    {
        for(int i=0; i<jLayeredPane2.getComponentCount(); i++) {
        jLayeredPane3.getComponent(i).setEnabled(false);
        jLayeredPane2.getComponent(i).setEnabled(false);
        }
        for(int i=0;i<jLayeredPane4.getComponentCount();i++){
        jLayeredPane4.getComponent(i).setEnabled(false);
        }
    }
     try
    {
        String x,r,no;
        rs=s1.executeQuery("select * from seats");
        while(rs.next())
        {
           x=rs.getString("S_no");
           r=x.substring(1);
           int a=Integer.parseInt(r);
           if(x.charAt(0)=='A'||x.charAt(0)=='B')
           {
               jLayeredPane2.
           }
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
}                                          

private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {                                     
// TODO add your handling code here:
    
}                                    

private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
// TODO add your handling code here:
       if(flag[11])
{
    jButton11.setBackground(new Color(240, 240, 240));
    flag[11] = false;
}else {
    jButton11.setBackground(new Color(255, 0, 0));
    flag[11] = true;
} 
}                                         

private void jLayeredPane3MouseClicked(java.awt.event.MouseEvent evt) {                                           
// TODO add your handling code here:
//   jLayeredPane3.get
    
}                                          

private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {                                          
if (flag[26])
{
    jButton26.setBackground(new Color(240, 240, 240));
    flag[26] = false;
}else {
    jButton26.setBackground(new Color(255, 0, 0));
    flag[26] = true;
}
}                                         

private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
// TODO add your handling code here:
}                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new copyseat().setVisible(true);
            }
        });
       
    }
    // Variables declaration - do not modify
    private javax.swing.JButton A2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration
}
